<#
.SYNOPSIS
    Register (or unregister) a Windows Startup shortcut that keeps the
    Vite dev server alive whenever the current user is logged in.

.DESCRIPTION
    Installs:
      %APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\
        PNM Tech Radar Dev Server.lnk

    The shortcut launches a hidden wscript.exe → serve-hidden.vbs →
    node.exe → scripts/serve.mjs supervisor. No console window flashes,
    no admin privileges required, no scheduled tasks needed.

.PARAMETER Uninstall
    Remove the shortcut and helper .vbs; leave everything else intact.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts/register-autostart.ps1
    powershell -ExecutionPolicy Bypass -File scripts/register-autostart.ps1 -Uninstall
#>
param([switch]$Uninstall)

$ErrorActionPreference = "Stop"
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptRoot
$startupDir = [Environment]::GetFolderPath("Startup")
$shortcutPath = Join-Path $startupDir "PNM Tech Radar Dev Server.lnk"
$vbsPath = Join-Path $scriptRoot "serve-hidden.vbs"

if ($Uninstall) {
    if (Test-Path $shortcutPath) {
        Remove-Item $shortcutPath -Force
        Write-Host "Removed shortcut: $shortcutPath"
    }
    if (Test-Path $vbsPath) {
        Remove-Item $vbsPath -Force
        Write-Host "Removed helper: $vbsPath"
    }
    Write-Host "The dev server will NOT auto-start at next login."
    exit 0
}

# Locate node.exe — prefer PATH, fall back to standard install location.
$node = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $node) { $node = Join-Path $env:ProgramFiles "nodejs\node.exe" }
if (-not (Test-Path $node)) {
    Write-Error "node.exe not found. Install Node.js first."
    exit 1
}

$servePath = Join-Path $scriptRoot "serve.mjs"
if (-not (Test-Path $servePath)) {
    Write-Error "Missing serve.mjs at $servePath"
    exit 1
}

# Build the hidden launcher. `shell.Run(..., 0, False)` means:
#   0     = window style: hidden
#   False = do not wait for exit
$vbs = @"
' Auto-generated by register-autostart.ps1 — do not edit by hand.
' Launches the Vite dev-server supervisor with no visible window.
Set shell = CreateObject("WScript.Shell")
shell.CurrentDirectory = "$projectRoot"
shell.Run """$node"" ""$servePath""", 0, False
"@
Set-Content -Path $vbsPath -Value $vbs -Encoding ASCII

# Startup folder .lnk pointing at wscript.exe running the .vbs.
$ws = New-Object -ComObject WScript.Shell
$shortcut = $ws.CreateShortcut($shortcutPath)
$shortcut.TargetPath = Join-Path $env:SystemRoot "System32\wscript.exe"
$shortcut.Arguments = "`"$vbsPath`""
$shortcut.WorkingDirectory = $projectRoot
$shortcut.WindowStyle = 7  # minimized
$shortcut.Description = "Keeps the PNM Tech Radar Vite dev server running on port 5173"
$shortcut.Save()

Write-Host "Installed autostart shortcut:"
Write-Host "  $shortcutPath"
Write-Host ""
Write-Host "The Vite dev server will now launch automatically at every login."
Write-Host "It's already running now (or will be after the next launch)."
Write-Host ""
Write-Host "To disable:"
Write-Host "  npm run autostart:disable"
