' Auto-generated by register-autostart.ps1 ??? do not edit by hand.
' Launches the Vite dev-server supervisor with no visible window.
Set shell = CreateObject("WScript.Shell")
shell.CurrentDirectory = "C:\Tech Radar Tools"
shell.Run """C:\Program Files\nodejs\node.exe"" ""C:\Tech Radar Tools\scripts\serve.mjs""", 0, False
