/**
 * Technology taxonomy — the classification model.
 *
 * Each entry maps a canonical technology to one of the four frontend
 * quadrants. `aliases` list every phrase the extractor should recognise
 * in article titles, tags, and repository names.
 *
 * Rules:
 *  - `slug` is a lowercase kebab identifier and MUST be unique.
 *  - `name` is the display label rendered as the blip name.
 *  - `aliases` must be lowercase; matcher is case-insensitive.
 *  - `quadrant` MUST be one of the four IDs defined in the frontend
 *    (radarConfig.ts). Never invent quadrants.
 *
 * Adding a technology here IS the act of classifying it — if it's not in
 * the taxonomy, the pipeline will not emit a blip for it. This satisfies
 * "Never guess. Classification must be explainable."
 */

/** @typedef {"infrastructure"|"ai-automation"|"security"|"data-integration"} QuadrantId */
/** @typedef {{ slug: string, name: string, aliases: string[], quadrant: QuadrantId }} TaxonomyEntry */

/** @type {TaxonomyEntry[]} */
export const TAXONOMY = [
  // ── Infrastructure — clouds, orchestration, IaC, edge, DevOps, observability ─
  { slug: "kubernetes", name: "Kubernetes", quadrant: "infrastructure", aliases: ["kubernetes", "k8s", "kube"], repo: "kubernetes/kubernetes" },
  { slug: "docker", name: "Docker", quadrant: "infrastructure", aliases: ["docker"], repo: "moby/moby" },
  { slug: "podman", name: "Podman", quadrant: "infrastructure", aliases: ["podman"] },
  { slug: "containerd", name: "containerd", quadrant: "infrastructure", aliases: ["containerd"], repo: "containerd/containerd" },
  { slug: "helm", name: "Helm", quadrant: "infrastructure", aliases: ["helm chart", "helm charts", "helm"] },
  { slug: "k3s", name: "k3s", quadrant: "infrastructure", aliases: ["k3s"], repo: "k3s-io/k3s" },
  { slug: "openshift", name: "OpenShift", quadrant: "infrastructure", aliases: ["openshift"] },
  { slug: "rancher", name: "Rancher", quadrant: "infrastructure", aliases: ["rancher"] },
  { slug: "nomad", name: "HashiCorp Nomad", quadrant: "infrastructure", aliases: ["hashicorp nomad", "nomad"] },
  { slug: "istio", name: "Istio", quadrant: "infrastructure", aliases: ["istio"] },
  { slug: "linkerd", name: "Linkerd", quadrant: "infrastructure", aliases: ["linkerd"] },
  { slug: "envoy", name: "Envoy", quadrant: "infrastructure", aliases: ["envoy proxy", "envoy"] },
  { slug: "nginx", name: "Nginx", quadrant: "infrastructure", aliases: ["nginx"] },
  { slug: "haproxy", name: "HAProxy", quadrant: "infrastructure", aliases: ["haproxy"] },
  { slug: "traefik", name: "Traefik", quadrant: "infrastructure", aliases: ["traefik"], repo: "traefik/traefik" },
  { slug: "caddy", name: "Caddy", quadrant: "infrastructure", aliases: ["caddy server", "caddy"], repo: "caddyserver/caddy" },
  { slug: "terraform", name: "Terraform", quadrant: "infrastructure", aliases: ["terraform"] },
  { slug: "opentofu", name: "OpenTofu", quadrant: "infrastructure", aliases: ["opentofu"] },
  { slug: "pulumi", name: "Pulumi", quadrant: "infrastructure", aliases: ["pulumi"] },
  { slug: "ansible", name: "Ansible", quadrant: "infrastructure", aliases: ["ansible"] },
  { slug: "chef", name: "Chef", quadrant: "infrastructure", aliases: ["chef infra", "chef automate"] },
  { slug: "puppet", name: "Puppet", quadrant: "infrastructure", aliases: ["puppet enterprise", "puppet"] },
  { slug: "packer", name: "Packer", quadrant: "infrastructure", aliases: ["hashicorp packer", "packer"] },
  { slug: "vagrant", name: "Vagrant", quadrant: "infrastructure", aliases: ["vagrant"] },
  { slug: "aws", name: "AWS", quadrant: "infrastructure", aliases: ["amazon web services", "aws cloud", "aws"] },
  { slug: "aws-ec2", name: "Amazon EC2", quadrant: "infrastructure", aliases: ["amazon ec2", "aws ec2", "ec2"] },
  { slug: "aws-s3", name: "AWS S3", quadrant: "infrastructure", aliases: ["amazon s3", "aws s3", "s3 bucket"] },
  { slug: "aws-lambda", name: "AWS Lambda", quadrant: "infrastructure", aliases: ["aws lambda", "amazon lambda"] },
  { slug: "aws-fargate", name: "AWS Fargate", quadrant: "infrastructure", aliases: ["aws fargate", "fargate"] },
  { slug: "aws-eks", name: "AWS EKS", quadrant: "infrastructure", aliases: ["aws eks", "amazon eks"] },
  { slug: "aws-ecs", name: "AWS ECS", quadrant: "infrastructure", aliases: ["aws ecs", "amazon ecs"] },
  { slug: "aws-cloudformation", name: "AWS CloudFormation", quadrant: "infrastructure", aliases: ["aws cloudformation", "cloudformation"] },
  { slug: "aws-cdk", name: "AWS CDK", quadrant: "infrastructure", aliases: ["aws cdk", "aws cloud development kit"] },
  { slug: "gcp", name: "Google Cloud", quadrant: "infrastructure", aliases: ["google cloud platform", "google cloud", "gcp"] },
  { slug: "gke", name: "Google Kubernetes Engine", quadrant: "infrastructure", aliases: ["google kubernetes engine", "gke"] },
  { slug: "gce", name: "Google Compute Engine", quadrant: "infrastructure", aliases: ["google compute engine"] },
  { slug: "azure", name: "Microsoft Azure", quadrant: "infrastructure", aliases: ["microsoft azure", "azure cloud", "azure"] },
  { slug: "azure-aks", name: "Azure Kubernetes Service", quadrant: "infrastructure", aliases: ["azure kubernetes service", "aks"] },
  { slug: "azure-functions", name: "Azure Functions", quadrant: "infrastructure", aliases: ["azure functions"] },
  { slug: "cloudflare", name: "Cloudflare", quadrant: "infrastructure", aliases: ["cloudflare"] },
  { slug: "cloudflare-workers", name: "Cloudflare Workers", quadrant: "infrastructure", aliases: ["cloudflare workers"] },
  { slug: "vercel", name: "Vercel", quadrant: "infrastructure", aliases: ["vercel"] },
  { slug: "netlify", name: "Netlify", quadrant: "infrastructure", aliases: ["netlify"] },
  { slug: "fly-io", name: "Fly.io", quadrant: "infrastructure", aliases: ["fly.io"] },
  { slug: "railway", name: "Railway", quadrant: "infrastructure", aliases: ["railway.app"] },
  { slug: "render", name: "Render", quadrant: "infrastructure", aliases: ["render.com"] },
  { slug: "digitalocean", name: "DigitalOcean", quadrant: "infrastructure", aliases: ["digitalocean"] },
  { slug: "linode", name: "Linode", quadrant: "infrastructure", aliases: ["linode"] },
  { slug: "hetzner", name: "Hetzner", quadrant: "infrastructure", aliases: ["hetzner"] },
  { slug: "github-actions", name: "GitHub Actions", quadrant: "infrastructure", aliases: ["github actions"] },
  { slug: "gitlab-ci", name: "GitLab CI", quadrant: "infrastructure", aliases: ["gitlab ci", "gitlab cicd", "gitlab-ci"] },
  { slug: "jenkins", name: "Jenkins", quadrant: "infrastructure", aliases: ["jenkins pipeline", "jenkins"] },
  { slug: "circleci", name: "CircleCI", quadrant: "infrastructure", aliases: ["circleci"] },
  { slug: "argocd", name: "Argo CD", quadrant: "infrastructure", aliases: ["argo cd", "argocd"] },
  { slug: "flux", name: "Flux CD", quadrant: "infrastructure", aliases: ["fluxcd", "flux cd"] },
  { slug: "tekton", name: "Tekton", quadrant: "infrastructure", aliases: ["tekton pipelines", "tekton"] },
  { slug: "buildkite", name: "Buildkite", quadrant: "infrastructure", aliases: ["buildkite"] },
  { slug: "prometheus", name: "Prometheus", quadrant: "infrastructure", aliases: ["prometheus"] },
  { slug: "grafana", name: "Grafana", quadrant: "infrastructure", aliases: ["grafana"] },
  { slug: "opentelemetry", name: "OpenTelemetry", quadrant: "infrastructure", aliases: ["opentelemetry", "otel"] },
  { slug: "jaeger", name: "Jaeger", quadrant: "infrastructure", aliases: ["jaegertracing", "jaeger"] },
  { slug: "loki", name: "Grafana Loki", quadrant: "infrastructure", aliases: ["grafana loki"] },
  { slug: "tempo", name: "Grafana Tempo", quadrant: "infrastructure", aliases: ["grafana tempo"] },
  { slug: "datadog", name: "Datadog", quadrant: "infrastructure", aliases: ["datadog"] },
  { slug: "new-relic", name: "New Relic", quadrant: "infrastructure", aliases: ["new relic"] },
  { slug: "honeycomb", name: "Honeycomb", quadrant: "infrastructure", aliases: ["honeycomb.io"] },
  { slug: "sentry", name: "Sentry", quadrant: "infrastructure", aliases: ["sentry.io"] },
  { slug: "pagerduty", name: "PagerDuty", quadrant: "infrastructure", aliases: ["pagerduty"] },
  { slug: "wasm", name: "WebAssembly", quadrant: "infrastructure", aliases: ["webassembly", "wasm"] },
  { slug: "wasi", name: "WASI", quadrant: "infrastructure", aliases: ["wasi"] },
  { slug: "ebpf", name: "eBPF", quadrant: "infrastructure", aliases: ["ebpf"] },
  { slug: "cilium", name: "Cilium", quadrant: "infrastructure", aliases: ["cilium"] },
  { slug: "backstage", name: "Backstage", quadrant: "infrastructure", aliases: ["backstage.io", "spotify backstage"] },
  { slug: "coder", name: "Coder", quadrant: "infrastructure", aliases: ["coder.com"], repo: "coder/coder" },
  { slug: "devcontainers", name: "Dev Containers", quadrant: "infrastructure", aliases: ["dev containers", "devcontainer"] },
  { slug: "gitpod", name: "Gitpod", quadrant: "infrastructure", aliases: ["gitpod"] },
  { slug: "nix", name: "Nix", quadrant: "infrastructure", aliases: ["nix package manager", "nix flake"] },
  { slug: "nixos", name: "NixOS", quadrant: "infrastructure", aliases: ["nixos"], repo: "NixOS/nixpkgs" },
  { slug: "consul", name: "HashiCorp Consul", quadrant: "infrastructure", aliases: ["hashicorp consul", "consul"] },

  // ── AI & Automation — models, frameworks, orchestration, streaming, ML ────
  { slug: "openai", name: "OpenAI API", quadrant: "ai-automation", aliases: ["openai api", "openai"] },
  { slug: "gpt-4", name: "GPT-4", quadrant: "ai-automation", aliases: ["gpt-4", "gpt4", "gpt 4"] },
  { slug: "gpt-5", name: "GPT-5", quadrant: "ai-automation", aliases: ["gpt-5", "gpt5"] },
  { slug: "claude", name: "Anthropic Claude", quadrant: "ai-automation", aliases: ["anthropic claude", "claude ai", "claude"] },
  { slug: "gemini", name: "Google Gemini", quadrant: "ai-automation", aliases: ["google gemini", "gemini pro", "gemini api"] },
  { slug: "llama", name: "Llama", quadrant: "ai-automation", aliases: ["llama 3", "llama3", "meta llama", "llama"] },
  { slug: "mistral", name: "Mistral AI", quadrant: "ai-automation", aliases: ["mistral ai", "mistral"] },
  { slug: "deepseek", name: "DeepSeek", quadrant: "ai-automation", aliases: ["deepseek"] },
  { slug: "qwen", name: "Qwen", quadrant: "ai-automation", aliases: ["qwen"] },
  { slug: "phi", name: "Phi", quadrant: "ai-automation", aliases: ["microsoft phi", "phi-3", "phi3"] },
  { slug: "langchain", name: "LangChain", quadrant: "ai-automation", aliases: ["langchain"], repo: "langchain-ai/langchain" },
  { slug: "langgraph", name: "LangGraph", quadrant: "ai-automation", aliases: ["langgraph"] },
  { slug: "llamaindex", name: "LlamaIndex", quadrant: "ai-automation", aliases: ["llamaindex", "llama-index"] },
  { slug: "haystack", name: "Haystack", quadrant: "ai-automation", aliases: ["deepset haystack", "haystack framework"] },
  { slug: "dspy", name: "DSPy", quadrant: "ai-automation", aliases: ["dspy"] },
  { slug: "autogen", name: "AutoGen", quadrant: "ai-automation", aliases: ["microsoft autogen", "autogen"] },
  { slug: "crewai", name: "CrewAI", quadrant: "ai-automation", aliases: ["crewai"] },
  { slug: "ollama", name: "Ollama", quadrant: "ai-automation", aliases: ["ollama"] },
  { slug: "vllm", name: "vLLM", quadrant: "ai-automation", aliases: ["vllm"] },
  { slug: "llamacpp", name: "llama.cpp", quadrant: "ai-automation", aliases: ["llama.cpp"] },
  { slug: "huggingface", name: "Hugging Face", quadrant: "ai-automation", aliases: ["hugging face", "huggingface"] },
  { slug: "transformers", name: "Transformers", quadrant: "ai-automation", aliases: ["huggingface transformers", "transformers library"], repo: "huggingface/transformers" },
  { slug: "pytorch", name: "PyTorch", quadrant: "ai-automation", aliases: ["pytorch"] },
  { slug: "tensorflow", name: "TensorFlow", quadrant: "ai-automation", aliases: ["tensorflow"] },
  { slug: "jax", name: "JAX", quadrant: "ai-automation", aliases: ["google jax"], repo: "jax-ml/jax" },
  { slug: "scikit-learn", name: "scikit-learn", quadrant: "ai-automation", aliases: ["scikit-learn", "sklearn"] },
  { slug: "xgboost", name: "XGBoost", quadrant: "ai-automation", aliases: ["xgboost"] },
  { slug: "mlflow", name: "MLflow", quadrant: "ai-automation", aliases: ["mlflow"] },
  { slug: "wandb", name: "Weights & Biases", quadrant: "ai-automation", aliases: ["weights and biases", "weights & biases", "wandb"] },
  { slug: "kubeflow", name: "Kubeflow", quadrant: "ai-automation", aliases: ["kubeflow"] },
  { slug: "ray", name: "Ray", quadrant: "ai-automation", aliases: ["ray.io", "anyscale ray"] },
  { slug: "airflow", name: "Apache Airflow", quadrant: "ai-automation", aliases: ["apache airflow", "airflow"], repo: "apache/airflow" },
  { slug: "prefect", name: "Prefect", quadrant: "ai-automation", aliases: ["prefect.io"] },
  { slug: "dagster", name: "Dagster", quadrant: "ai-automation", aliases: ["dagster"] },
  { slug: "temporal", name: "Temporal", quadrant: "ai-automation", aliases: ["temporal.io", "temporal workflow"] },
  { slug: "n8n", name: "n8n", quadrant: "ai-automation", aliases: ["n8n"], repo: "n8n-io/n8n" },
  { slug: "zapier", name: "Zapier", quadrant: "ai-automation", aliases: ["zapier"] },
  { slug: "spark", name: "Apache Spark", quadrant: "ai-automation", aliases: ["apache spark"] },
  { slug: "flink", name: "Apache Flink", quadrant: "ai-automation", aliases: ["apache flink", "flink"] },
  { slug: "beam", name: "Apache Beam", quadrant: "ai-automation", aliases: ["apache beam"] },
  { slug: "kafka", name: "Apache Kafka", quadrant: "ai-automation", aliases: ["apache kafka", "kafka"], repo: "apache/kafka" },
  { slug: "pulsar", name: "Apache Pulsar", quadrant: "ai-automation", aliases: ["apache pulsar"] },
  { slug: "nats", name: "NATS", quadrant: "ai-automation", aliases: ["nats.io"], repo: "nats-io/nats-server" },
  { slug: "rabbitmq", name: "RabbitMQ", quadrant: "ai-automation", aliases: ["rabbitmq"] },
  { slug: "redpanda", name: "Redpanda", quadrant: "ai-automation", aliases: ["redpanda"] },
  { slug: "databricks", name: "Databricks", quadrant: "ai-automation", aliases: ["databricks"] },
  { slug: "sagemaker", name: "AWS SageMaker", quadrant: "ai-automation", aliases: ["aws sagemaker", "amazon sagemaker"] },
  { slug: "bedrock", name: "AWS Bedrock", quadrant: "ai-automation", aliases: ["aws bedrock", "amazon bedrock"] },
  { slug: "vertex-ai", name: "Vertex AI", quadrant: "ai-automation", aliases: ["google vertex ai", "vertex ai"] },
  { slug: "openai-agents", name: "OpenAI Agents SDK", quadrant: "ai-automation", aliases: ["openai agents", "agents sdk"] },
  { slug: "rag", name: "Retrieval-Augmented Generation", quadrant: "ai-automation", aliases: ["retrieval augmented generation", "retrieval-augmented generation", "rag pipeline"] },
  { slug: "copilot", name: "GitHub Copilot", quadrant: "ai-automation", aliases: ["github copilot", "copilot chat"] },
  { slug: "cursor", name: "Cursor", quadrant: "ai-automation", aliases: ["cursor editor", "cursor ai"] },
  { slug: "windsurf", name: "Windsurf", quadrant: "ai-automation", aliases: ["windsurf editor", "codeium windsurf"] },
  { slug: "claude-code", name: "Claude Code", quadrant: "ai-automation", aliases: ["claude code"] },
  { slug: "mcp", name: "Model Context Protocol", quadrant: "ai-automation", aliases: ["model context protocol", "mcp server"] },
  { slug: "streamlit", name: "Streamlit", quadrant: "ai-automation", aliases: ["streamlit"] },
  { slug: "gradio", name: "Gradio", quadrant: "ai-automation", aliases: ["gradio"] },

  // ── Security — identity, secrets, scanning, runtime, zero-trust, encryption
  { slug: "vault", name: "HashiCorp Vault", quadrant: "security", aliases: ["hashicorp vault"] },
  { slug: "aws-iam", name: "AWS IAM", quadrant: "security", aliases: ["aws iam", "amazon iam"] },
  { slug: "aws-waf", name: "AWS WAF", quadrant: "security", aliases: ["aws waf"] },
  { slug: "aws-shield", name: "AWS Shield", quadrant: "security", aliases: ["aws shield"] },
  { slug: "aws-secrets-manager", name: "AWS Secrets Manager", quadrant: "security", aliases: ["aws secrets manager"] },
  { slug: "aws-guardduty", name: "AWS GuardDuty", quadrant: "security", aliases: ["aws guardduty"] },
  { slug: "okta", name: "Okta", quadrant: "security", aliases: ["okta"] },
  { slug: "auth0", name: "Auth0", quadrant: "security", aliases: ["auth0"] },
  { slug: "keycloak", name: "Keycloak", quadrant: "security", aliases: ["keycloak"] },
  { slug: "clerk", name: "Clerk", quadrant: "security", aliases: ["clerk.dev", "clerk.com"] },
  { slug: "supertokens", name: "SuperTokens", quadrant: "security", aliases: ["supertokens"] },
  { slug: "opa", name: "Open Policy Agent", quadrant: "security", aliases: ["open policy agent", "opa gatekeeper"] },
  { slug: "cedar", name: "Cedar", quadrant: "security", aliases: ["cedar policy", "aws cedar"] },
  { slug: "spiffe", name: "SPIFFE", quadrant: "security", aliases: ["spiffe", "spire"] },
  { slug: "passkeys", name: "Passkeys", quadrant: "security", aliases: ["passkeys", "webauthn", "fido2"] },
  { slug: "oidc", name: "OpenID Connect", quadrant: "security", aliases: ["openid connect", "oidc"] },
  { slug: "oauth2", name: "OAuth 2.0", quadrant: "security", aliases: ["oauth 2.0", "oauth2"] },
  { slug: "snyk", name: "Snyk", quadrant: "security", aliases: ["snyk"] },
  { slug: "trivy", name: "Trivy", quadrant: "security", aliases: ["aquasec trivy", "trivy"], repo: "aquasecurity/trivy" },
  { slug: "grype", name: "Grype", quadrant: "security", aliases: ["anchore grype", "grype"] },
  { slug: "semgrep", name: "Semgrep", quadrant: "security", aliases: ["semgrep"] },
  { slug: "codeql", name: "CodeQL", quadrant: "security", aliases: ["codeql"] },
  { slug: "sonarqube", name: "SonarQube", quadrant: "security", aliases: ["sonarqube", "sonarcloud"] },
  { slug: "checkov", name: "Checkov", quadrant: "security", aliases: ["checkov"] },
  { slug: "falco", name: "Falco", quadrant: "security", aliases: ["falco security", "falco"] },
  { slug: "wiz", name: "Wiz", quadrant: "security", aliases: ["wiz.io", "wiz security"] },
  { slug: "aqua-security", name: "Aqua Security", quadrant: "security", aliases: ["aqua security"] },
  { slug: "sysdig", name: "Sysdig", quadrant: "security", aliases: ["sysdig"] },
  { slug: "prisma-cloud", name: "Prisma Cloud", quadrant: "security", aliases: ["prisma cloud"] },
  { slug: "crowdstrike", name: "CrowdStrike", quadrant: "security", aliases: ["crowdstrike"] },
  { slug: "sentinelone", name: "SentinelOne", quadrant: "security", aliases: ["sentinelone"] },
  { slug: "sigstore", name: "Sigstore", quadrant: "security", aliases: ["sigstore"] },
  { slug: "cosign", name: "Cosign", quadrant: "security", aliases: ["sigstore cosign", "cosign"], repo: "sigstore/cosign" },
  { slug: "sbom", name: "SBOM", quadrant: "security", aliases: ["software bill of materials", "cyclonedx", "spdx sbom", "sbom"] },
  { slug: "slsa", name: "SLSA", quadrant: "security", aliases: ["supply chain levels for software artifacts", "slsa"] },
  { slug: "teleport", name: "Teleport", quadrant: "security", aliases: ["gravitational teleport", "teleport"] },
  { slug: "hashicorp-boundary", name: "HashiCorp Boundary", quadrant: "security", aliases: ["hashicorp boundary"] },
  { slug: "cloudflare-access", name: "Cloudflare Access", quadrant: "security", aliases: ["cloudflare access", "cloudflare zero trust"] },
  { slug: "tailscale", name: "Tailscale", quadrant: "security", aliases: ["tailscale"], repo: "tailscale/tailscale" },
  { slug: "wireguard", name: "WireGuard", quadrant: "security", aliases: ["wireguard"] },
  { slug: "1password", name: "1Password", quadrant: "security", aliases: ["1password"] },
  { slug: "bitwarden", name: "Bitwarden", quadrant: "security", aliases: ["bitwarden"], repo: "bitwarden/server" },
  { slug: "doppler", name: "Doppler", quadrant: "security", aliases: ["doppler secrets"] },
  { slug: "infisical", name: "Infisical", quadrant: "security", aliases: ["infisical"], repo: "Infisical/infisical" },
  { slug: "age", name: "age (encryption)", quadrant: "security", aliases: ["age encryption", "filippo age"] },
  { slug: "postquantum", name: "Post-Quantum Cryptography", quadrant: "security", aliases: ["post-quantum cryptography", "post quantum crypto", "ml-kem", "kyber"] },
  { slug: "kubernetes-rbac", name: "Kubernetes RBAC", quadrant: "security", aliases: ["kubernetes rbac"] },
  { slug: "cve", name: "CVE Advisory", quadrant: "security", aliases: ["cve-", "cve "] },
  { slug: "zero-trust", name: "Zero Trust", quadrant: "security", aliases: ["zero trust architecture", "zero-trust", "zero trust"] },
  { slug: "supply-chain-security", name: "Supply-Chain Security", quadrant: "security", aliases: ["supply chain security", "supply-chain attack", "supply chain attack"] },
  { slug: "ransomware", name: "Ransomware Defense", quadrant: "security", aliases: ["ransomware"] },

  // ── Data & Integration — databases, APIs, languages, frameworks, streaming ─
  { slug: "postgresql", name: "PostgreSQL", quadrant: "data-integration", aliases: ["postgresql", "postgres"], repo: "postgres/postgres" },
  { slug: "mysql", name: "MySQL", quadrant: "data-integration", aliases: ["mysql"] },
  { slug: "mariadb", name: "MariaDB", quadrant: "data-integration", aliases: ["mariadb"] },
  { slug: "sqlite", name: "SQLite", quadrant: "data-integration", aliases: ["sqlite"] },
  { slug: "mongodb", name: "MongoDB", quadrant: "data-integration", aliases: ["mongodb"] },
  { slug: "redis", name: "Redis", quadrant: "data-integration", aliases: ["redis"] },
  { slug: "valkey", name: "Valkey", quadrant: "data-integration", aliases: ["valkey"] },
  { slug: "memcached", name: "Memcached", quadrant: "data-integration", aliases: ["memcached"] },
  { slug: "cassandra", name: "Apache Cassandra", quadrant: "data-integration", aliases: ["apache cassandra", "cassandra"] },
  { slug: "scylladb", name: "ScyllaDB", quadrant: "data-integration", aliases: ["scylladb"] },
  { slug: "elasticsearch", name: "Elasticsearch", quadrant: "data-integration", aliases: ["elasticsearch"] },
  { slug: "opensearch", name: "OpenSearch", quadrant: "data-integration", aliases: ["opensearch"] },
  { slug: "clickhouse", name: "ClickHouse", quadrant: "data-integration", aliases: ["clickhouse"], repo: "ClickHouse/ClickHouse" },
  { slug: "duckdb", name: "DuckDB", quadrant: "data-integration", aliases: ["duckdb"] },
  { slug: "snowflake", name: "Snowflake", quadrant: "data-integration", aliases: ["snowflake cloud", "snowflake data cloud", "snowflake"] },
  { slug: "bigquery", name: "Google BigQuery", quadrant: "data-integration", aliases: ["google bigquery", "bigquery"] },
  { slug: "cockroachdb", name: "CockroachDB", quadrant: "data-integration", aliases: ["cockroachdb"] },
  { slug: "yugabytedb", name: "YugabyteDB", quadrant: "data-integration", aliases: ["yugabytedb", "yugabyte"] },
  { slug: "tidb", name: "TiDB", quadrant: "data-integration", aliases: ["pingcap tidb", "tidb"] },
  { slug: "surrealdb", name: "SurrealDB", quadrant: "data-integration", aliases: ["surrealdb"] },
  { slug: "turso", name: "Turso", quadrant: "data-integration", aliases: ["turso"] },
  { slug: "planetscale", name: "PlanetScale", quadrant: "data-integration", aliases: ["planetscale"] },
  { slug: "supabase", name: "Supabase", quadrant: "data-integration", aliases: ["supabase"], repo: "supabase/supabase" },
  { slug: "neon", name: "Neon", quadrant: "data-integration", aliases: ["neon.tech", "neon postgres"] },
  { slug: "convex", name: "Convex", quadrant: "data-integration", aliases: ["convex.dev"] },
  { slug: "firebase", name: "Firebase", quadrant: "data-integration", aliases: ["google firebase", "firebase"] },
  { slug: "dynamodb", name: "Amazon DynamoDB", quadrant: "data-integration", aliases: ["amazon dynamodb", "dynamodb"] },
  { slug: "neo4j", name: "Neo4j", quadrant: "data-integration", aliases: ["neo4j"] },
  { slug: "pinecone", name: "Pinecone", quadrant: "data-integration", aliases: ["pinecone vector"] },
  { slug: "weaviate", name: "Weaviate", quadrant: "data-integration", aliases: ["weaviate"] },
  { slug: "milvus", name: "Milvus", quadrant: "data-integration", aliases: ["milvus"], repo: "milvus-io/milvus" },
  { slug: "qdrant", name: "Qdrant", quadrant: "data-integration", aliases: ["qdrant"] },
  { slug: "chromadb", name: "Chroma", quadrant: "data-integration", aliases: ["chromadb", "chroma vector"] },
  { slug: "lancedb", name: "LanceDB", quadrant: "data-integration", aliases: ["lancedb"] },
  { slug: "iceberg", name: "Apache Iceberg", quadrant: "data-integration", aliases: ["apache iceberg"] },
  { slug: "delta-lake", name: "Delta Lake", quadrant: "data-integration", aliases: ["delta lake"] },
  { slug: "dbt", name: "dbt", quadrant: "data-integration", aliases: ["dbt-core", "dbt cloud", "dbt labs"] },
  { slug: "airbyte", name: "Airbyte", quadrant: "data-integration", aliases: ["airbyte"] },
  { slug: "fivetran", name: "Fivetran", quadrant: "data-integration", aliases: ["fivetran"] },
  { slug: "graphql", name: "GraphQL", quadrant: "data-integration", aliases: ["graphql"] },
  { slug: "grpc", name: "gRPC", quadrant: "data-integration", aliases: ["grpc"] },
  { slug: "trpc", name: "tRPC", quadrant: "data-integration", aliases: ["trpc"] },
  { slug: "openapi", name: "OpenAPI", quadrant: "data-integration", aliases: ["openapi", "swagger spec", "openapi specification"] },
  { slug: "asyncapi", name: "AsyncAPI", quadrant: "data-integration", aliases: ["asyncapi"] },
  { slug: "typescript", name: "TypeScript", quadrant: "data-integration", aliases: ["typescript"], repo: "microsoft/TypeScript" },
  { slug: "javascript", name: "JavaScript", quadrant: "data-integration", aliases: ["javascript"] },
  { slug: "python", name: "Python", quadrant: "data-integration", aliases: ["python 3", "python"], repo: "python/cpython" },
  { slug: "go", name: "Go", quadrant: "data-integration", aliases: ["golang"], repo: "golang/go" },
  { slug: "rust", name: "Rust", quadrant: "data-integration", aliases: ["rust language", "rustlang"], repo: "rust-lang/rust" },
  { slug: "java", name: "Java", quadrant: "data-integration", aliases: ["java 21", "java language"], repo: "openjdk/jdk" },
  { slug: "kotlin", name: "Kotlin", quadrant: "data-integration", aliases: ["kotlin"], repo: "JetBrains/kotlin" },
  { slug: "swift", name: "Swift", quadrant: "data-integration", aliases: ["swift language"], repo: "swiftlang/swift" },
  { slug: "csharp", name: "C#", quadrant: "data-integration", aliases: ["c# language", " c# "] },
  { slug: "dotnet", name: ".NET", quadrant: "data-integration", aliases: [".net 8", ".net 9", ".net core", ".net"] },
  { slug: "elixir", name: "Elixir", quadrant: "data-integration", aliases: ["elixir language"] },
  { slug: "phoenix-framework", name: "Phoenix Framework", quadrant: "data-integration", aliases: ["phoenix framework", "phoenix liveview"] },
  { slug: "zig", name: "Zig", quadrant: "data-integration", aliases: ["zig language", "ziglang"] },
  { slug: "dart", name: "Dart", quadrant: "data-integration", aliases: ["dart language"], repo: "dart-lang/sdk" },
  { slug: "ruby", name: "Ruby", quadrant: "data-integration", aliases: ["ruby language"] },
  { slug: "rails", name: "Ruby on Rails", quadrant: "data-integration", aliases: ["ruby on rails", "rails 7", "rails 8"] },
  { slug: "php", name: "PHP", quadrant: "data-integration", aliases: ["php 8"], repo: "php/php-src" },
  { slug: "laravel", name: "Laravel", quadrant: "data-integration", aliases: ["laravel"] },
  { slug: "react", name: "React", quadrant: "data-integration", aliases: ["react.js", "reactjs", "react 19"], repo: "react/react" },
  { slug: "nextjs", name: "Next.js", quadrant: "data-integration", aliases: ["next.js", "nextjs"] },
  { slug: "remix", name: "Remix", quadrant: "data-integration", aliases: ["remix run", "remix.run"] },
  { slug: "vue", name: "Vue.js", quadrant: "data-integration", aliases: ["vue.js", "vuejs", "vue 3"], repo: "vuejs/core" },
  { slug: "nuxt", name: "Nuxt", quadrant: "data-integration", aliases: ["nuxt.js", "nuxtjs"] },
  { slug: "svelte", name: "Svelte", quadrant: "data-integration", aliases: ["svelte"], repo: "sveltejs/svelte" },
  { slug: "sveltekit", name: "SvelteKit", quadrant: "data-integration", aliases: ["sveltekit"] },
  { slug: "solidjs", name: "SolidJS", quadrant: "data-integration", aliases: ["solid.js", "solidjs"] },
  { slug: "qwik", name: "Qwik", quadrant: "data-integration", aliases: ["qwik framework"] },
  { slug: "astro", name: "Astro", quadrant: "data-integration", aliases: ["astro.build", "astrojs"], repo: "withastro/astro" },
  { slug: "angular", name: "Angular", quadrant: "data-integration", aliases: ["angular framework"] },
  { slug: "htmx", name: "HTMX", quadrant: "data-integration", aliases: ["htmx"] },
  { slug: "alpinejs", name: "Alpine.js", quadrant: "data-integration", aliases: ["alpine.js", "alpinejs"] },
  { slug: "tailwindcss", name: "Tailwind CSS", quadrant: "data-integration", aliases: ["tailwind css", "tailwindcss"], repo: "tailwindlabs/tailwindcss" },
  { slug: "vite", name: "Vite", quadrant: "data-integration", aliases: ["vite.js"], repo: "vitejs/vite" },
  { slug: "turbopack", name: "Turbopack", quadrant: "data-integration", aliases: ["turbopack"] },
  { slug: "webpack", name: "Webpack", quadrant: "data-integration", aliases: ["webpack"] },
  { slug: "esbuild", name: "esbuild", quadrant: "data-integration", aliases: ["esbuild"], repo: "evanw/esbuild" },
  { slug: "rollup", name: "Rollup", quadrant: "data-integration", aliases: ["rollup.js"] },
  { slug: "biome", name: "Biome", quadrant: "data-integration", aliases: ["biomejs", "biome.js"] },
  { slug: "eslint", name: "ESLint", quadrant: "data-integration", aliases: ["eslint"] },
  { slug: "prettier", name: "Prettier", quadrant: "data-integration", aliases: ["prettier"] },
  { slug: "nodejs", name: "Node.js", quadrant: "data-integration", aliases: ["node.js", "nodejs"] },
  { slug: "deno", name: "Deno", quadrant: "data-integration", aliases: ["deno"] },
  { slug: "bun", name: "Bun", quadrant: "data-integration", aliases: ["bun runtime", "bun.sh"], repo: "oven-sh/bun" },
  { slug: "express", name: "Express", quadrant: "data-integration", aliases: ["express.js", "expressjs"] },
  { slug: "fastify", name: "Fastify", quadrant: "data-integration", aliases: ["fastify"], repo: "fastify/fastify" },
  { slug: "hono", name: "Hono", quadrant: "data-integration", aliases: ["honojs", "hono.js"] },
  { slug: "nestjs", name: "NestJS", quadrant: "data-integration", aliases: ["nest.js", "nestjs"], repo: "nestjs/nest" },
  { slug: "fastapi", name: "FastAPI", quadrant: "data-integration", aliases: ["fastapi"] },
  { slug: "django", name: "Django", quadrant: "data-integration", aliases: ["django framework"] },
  { slug: "flask", name: "Flask", quadrant: "data-integration", aliases: ["flask framework"] },
  { slug: "spring", name: "Spring", quadrant: "data-integration", aliases: ["spring boot", "spring framework"] },
  { slug: "aspnet", name: "ASP.NET", quadrant: "data-integration", aliases: ["asp.net"] },
  { slug: "gin", name: "Gin", quadrant: "data-integration", aliases: ["gin framework", "gin-gonic"] },
  { slug: "echo", name: "Echo (Go)", quadrant: "data-integration", aliases: ["echo framework"] },
  { slug: "axum", name: "Axum", quadrant: "data-integration", aliases: ["tokio axum", "axum framework"] },
  { slug: "actix", name: "Actix Web", quadrant: "data-integration", aliases: ["actix-web", "actix web"] },
  { slug: "flutter", name: "Flutter", quadrant: "data-integration", aliases: ["flutter"] },
  { slug: "react-native", name: "React Native", quadrant: "data-integration", aliases: ["react native"] },
  { slug: "expo", name: "Expo", quadrant: "data-integration", aliases: ["expo.dev", "expo router"] },
  { slug: "tauri", name: "Tauri", quadrant: "data-integration", aliases: ["tauri.app"] },
  { slug: "electron", name: "Electron", quadrant: "data-integration", aliases: ["electron js"], repo: "electron/electron" },
  { slug: "playwright", name: "Playwright", quadrant: "data-integration", aliases: ["playwright test", "microsoft playwright"] },
  { slug: "cypress", name: "Cypress", quadrant: "data-integration", aliases: ["cypress.io"] },
  { slug: "vitest", name: "Vitest", quadrant: "data-integration", aliases: ["vitest"] },
  { slug: "jest", name: "Jest", quadrant: "data-integration", aliases: ["jest testing"] },
  { slug: "storybook", name: "Storybook", quadrant: "data-integration", aliases: ["storybookjs", "storybook.js"] },
  { slug: "prisma", name: "Prisma ORM", quadrant: "data-integration", aliases: ["prisma orm", "prisma client"] },
  { slug: "drizzle", name: "Drizzle ORM", quadrant: "data-integration", aliases: ["drizzle orm"] },
  { slug: "tanstack-query", name: "TanStack Query", quadrant: "data-integration", aliases: ["tanstack query", "react query"] },
  { slug: "zod", name: "Zod", quadrant: "data-integration", aliases: ["zod schema"], repo: "colinhacks/zod" },
  { slug: "shadcn-ui", name: "shadcn/ui", quadrant: "data-integration", aliases: ["shadcn/ui", "shadcn ui"] },
];

/** @type {Map<string, string>} slug → quadrant (fast lookup). */
export const SLUG_TO_QUADRANT = new Map(TAXONOMY.map((entry) => [entry.slug, entry.quadrant]));

/** @type {Map<string, TaxonomyEntry>} */
export const SLUG_TO_ENTRY = new Map(TAXONOMY.map((entry) => [entry.slug, entry]));

/** @type {Map<string, string>} lowercase alias → slug. Longest keys sorted first. */
export const ALIAS_TO_SLUG = (() => {
  const map = new Map();
  for (const entry of TAXONOMY) {
    for (const alias of entry.aliases) {
      map.set(alias.toLowerCase(), entry.slug);
    }
    // Also register the canonical name (case-insensitive).
    map.set(entry.name.toLowerCase(), entry.slug);
  }
  return map;
})();

/** All alias phrases, sorted longest-first — used to build the master regex. */
export const ALIASES_LONGEST_FIRST = [...ALIAS_TO_SLUG.keys()].sort(
  (a, b) => b.length - a.length,
);

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Master regex that matches any alias with word boundaries. Case-insensitive.
 * Sorted longest-first so "AWS Lambda" wins over "AWS" when both apply.
 */
export const ALIAS_REGEX = new RegExp(
  `\\b(?:${ALIASES_LONGEST_FIRST.map(escapeRegex).join("|")})\\b`,
  "gi",
);
